elements = [
    {symbol: "H", name: "idrogeno"},
    {symbol: null, spacing: 16},
    {symbol: "He", name: "elio"},

    {symbol: "Li", name: "litio"},
    {symbol: "Be", name: "berillio"},
    {symbol: null, spacing: 10},
    {symbol: "B", name: "boro"},
    {symbol: "C", name: "carbonio"},
    {symbol: "N", name: "azoto"},
    {symbol: "O", name: "ossigeno"},
    {symbol: "F", name: "fluoro"},
    {symbol: "Ne", name: "neon"},

    {symbol: "Na", name: "sodio"},
    {symbol: "Mg", name: "magnesio"},
    {symbol: null, spacing: 10},
    {symbol: "Al", name: "alluminio"},
    {symbol: "Si", name: "silicio"},
    {symbol: "P", name: "fosforo"},
    {symbol: "S", name: "zolfo"},
    {symbol: "Cl", name: "cloro"},
    {symbol: "Ar", name: "argon"},

    {symbol: "K", name: "potassio"},
    {symbol: "Ca", name: "calcio"},
    {symbol: "Sc", name: "scandio"},
    {symbol: "Ti", name: "titanio"},
    {symbol: "V", name: "vanadio"},
    {symbol: "Cr", name: "cromo"},
    {symbol: "Mn", name: "manganese"},
    {symbol: "Fe", name: "ferro"},
    {symbol: "Co", name: "cobalto"},
    {symbol: "Ni", name: "nichel"},
    {symbol: "Cu", name: "rame"},
    {symbol: "Zn", name: "zinco"},
    {symbol: "Ga", name: "gallio"},
    {symbol: "Ge", name: "germanio"},
    {symbol: "As", name: "arsenico"},
    {symbol: "Se", name: "selenio"},
    {symbol: "Br", name: "bromo"},
    {symbol: "Kr", name: "cripton"},

    {symbol: "Rb", name: "rubidio"},

]