elements = [
    {symbol: "H", name: "idrogeno", oxidation: "+-1"},
    {symbol: null, spacing: 16},
    {symbol: "He", name: "elio", oxidation: "--"},

    {symbol: "Li", name: "litio", oxidation: "+1"},
    {symbol: "Be", name: "berillio", oxidation: "+2"},
    {symbol: null, spacing: 10},
    {symbol: "B", name: "boro", oxidation: "+3"},
    {symbol: "C", name: "carbonio", oxidation: "+2+-4"},
    {symbol: "N", name: "azoto", oxidation: "+2+-3+4+5"},
    {symbol: "O", name: "ossigeno", oxidation: "-2"},
    {symbol: "F", name: "fluoro", oxidation: "-1"},
    {symbol: "Ne", name: "neon", oxidation: "--"},

    {symbol: "Na", name: "sodio", oxidation: "+1"},
    {symbol: "Mg", name: "magnesio", oxidation: "+2"},
    {symbol: null, spacing: 10},
    {symbol: "Al", name: "alluminio", oxidation: "+3"},
    {symbol: "Si", name: "silicio", oxidation: "+2+-4"},
    {symbol: "P", name: "fosforo", oxidation: "+-3+5"},
    {symbol: "S", name: "zolfo", oxidation: "-2+4+6"},
    {symbol: "Cl", name: "cloro", oxidation: "+-1+3+5+7"},
    {symbol: "Ar", name: "argon", oxidation: "--"},

    {symbol: "K", name: "potassio", oxidation: "+1"},
    {symbol: "Ca", name: "calcio", oxidation: "+2"},
    {symbol: "Sc", name: "scandio", oxidation: "+3"},
    {symbol: "Ti", name: "titanio", oxidation: "+2+3+4"},
    {symbol: "V", name: "vanadio", oxidation: "+2+3+4+5"},
    {symbol: "Cr", name: "cromo", oxidation: "+2+3+6"},
    {symbol: "Mn", name: "manganese", oxidation: "+2+3+4+6+7"},
    {symbol: "Fe", name: "ferro", oxidation: "+2+3"},
    {symbol: "Co", name: "cobalto", oxidation: "+2+3"},
    {symbol: "Ni", name: "nichel", oxidation: "+2+3"},
    {symbol: "Cu", name: "rame", oxidation: "+1+2"},
    {symbol: "Zn", name: "zinco", oxidation: "+2"},
    {symbol: "Ga", name: "gallio", oxidation: "+3"},
    {symbol: "Ge", name: "germanio", oxidation: "+2+4"},
    {symbol: "As", name: "arsenico", oxidation: "+-3+5"},
    {symbol: "Se", name: "selenio", oxidation: "-2+4+6"},
    {symbol: "Br", name: "bromo", oxidation: "+-1+3+5"},
    {symbol: "Kr", name: "cripton", oxidation: "--"},

    {symbol: "Rb", name: "rubidio", oxidation: "--"},

]